---
- name: Main
  hosts: workstation
  roles:
    - role: group_distributions
    - role: ohmyzsh
    - role: tmux
    - role: neovim
    - role: git
    - role: go
    - role: hashicorp
    - role: kubectl
    - role: helm
    - role: docker
      # Do not manage Docker in WSL, as it is managed by Docker Desktop on Windows.
      when: not is_wsl
    - role: k3d
    - role: kind
  tasks:
    - name: Nnn is present
      become: true
      github_release_asset:
        repo: jarun/nnn
        asset_pattern: nerd-static
    - name: Tilt is present
      become: true
      github_release_asset:
        repo: tilt-dev/tilt
        asset_pattern: linux\.x86_64
    - name: Vale is present
      become: true
      github_release_asset:
        repo: errata-ai/vale
        asset_pattern: Linux_64
    - name: Golangci-lint is present
      become: true
      github_release_asset:
        repo: golangci/golangci-lint
        asset_pattern: linux-386\.tar\.gz
    # TODO Add pdfcpu? Need lzma support in github_release_asset module.
