---
- hosts: localhost
  roles:
    - role: neovim
    - role: tmux
    - role: ohmyzsh
    - role: hashicorp
    - role: kubectl
    - role: helm
    - role: k3d
    # See dynamic role reuse as well.
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - role: github_archived_binary
      vars:
        repo: 'jarun/nnn'
        version: 'v4.4'
        executable_glob: 'nnn-static'
        asset_regex: 'nnn-static-.*\.x86_64\.tar\.gz'
        version_command: "/usr/bin/sh -c 'echo v$(nnn -V)'"
        dest: '/usr/local/bin/nnn'
    # - role: github_archived_binary
    #   vars:
    #     repo: 'pdfcpu/pdfcpu'
    #     version: 'v0.3.13'
    #     executable_glob: '*/pdfcpu'
    #     asset_regex: 'pdfcpu_.*_Linux_x86_64\.tar\.xz'
    #     version_command: "/usr/local/bin/pdfcpu version"
    #     dest: '/usr/local/bin/pdfcpu'
