---
docker_apt_key_url: https://download.docker.com/linux/debian/gpg
docker_apt_repository: >
  deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable

# Can also be used with Ubuntu 22.04:
# docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
# docker_apt_repository: >
#   deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
