---
- name: Keyrings folder is present
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "1755"

- name: Kubernetes keyring is present
  become: true
  ansible.builtin.get_url:
    url: "{{ kubectl_apt_key_url }}"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: "644"

- name: Kubernetes package repository is present
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ kubectl_apt_repository }}"

- name: Latest kubectl is installed
  become: true
  ansible.builtin.apt:
    name:
      - kubectl
    state: latest
    update_cache: true
