---
- name: Zsh and Git are installed
  become: true
  ansible.builtin.apt:
    name:
      - git
      - zsh
    state: latest

- name: Oh My Zsh repository is cloned
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: Repository permissions are correct
  ansible.builtin.file:
    path: ~/.oh-my-zsh
    mode: go-w
  
- name: Zsh is the default shell
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    shell: /bin/zsh

- name: Node Version Manager is cloned
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm
    dest: ~/.nvm

- name: fzf is installed for Zsh plugin
  become: true
  ansible.builtin.apt:
    name: fzf

- name: pip is installed for Poetry download
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Poetry is installed for Zsh plugin
  become: true
  ansible.builtin.pip:
    name: poetry
    state: latest

- name: is_wsl fact is set
  ansible.builtin.set_fact:
    is_wsl: "{{ not not (ansible_kernel | regex_search('microsoft')) }}"

- name: .zshrc is present
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: u=rw,go=r

- name: custom theme is present
  ansible.builtin.template:
    src: minima.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/minima.zsh-theme
    mode: u=rw,go=r
