---
- name: Tmux is installed
  become: true
  ansible.builtin.apt:
    name: tmux
    state: latest

- name: Plugins directory is present
  ansible.builtin.file:
    path: ~/.tmux/plugins
    state: directory
    mode: "1744"

- name: Tpm is present
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Config is present
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.tmux.conf
    mode: "644"

- name: Tmuxp is present
  community.general.pipx:
    name: tmuxp
    state: latest
