---
- name: Keyrings folder is present
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '1755'

- name: Hashicorp GPG key is present
  become: true
  ansible.builtin.get_url:
    url: '{{ hashicorp_apt_key_url }}'
    dest: /etc/apt/keyrings/hashicorp.asc

- name: Hashicorp package repository is present
  become: true
  ansible.builtin.apt_repository:
    repo: '{{ hashicorp_apt_repository }}'

- name: Latest Terraform and Packer are installed
  become: true
  ansible.builtin.apt:
    name:
      - terraform
      - packer
    state: latest
    update_cache: yes

- name: Latest Language Server is installed for NeoVim
  become: true
  ansible.builtin.apt:
    name:
      - terraform-ls
    state: latest
    update_cache: yes
