---
plugin: lkummer.homelab.terraform_local
tfstate_path: ../terraform/terraform.tfstate
hosts:
  - ansible_host: '{{ machine_ssh_ip }}'
    ansible_group: workstation
    vars:
      ansible_user: '{{ machine_ssh_user }}'
