---
plugin: lkummer.homelab.terraform_local
tfstate_path: ../terraform/terraform.tfstate
hosts:
  - ansible_host: '{{ ssh_ip }}'
    ansible_group: workstation
    ansible_port: '22'
    vars:
      ansible_user: '{{ ssh_user }}'
