---
- name: Get NeoVim version
  ansible.builtin.command: nvim --version
  ignore_errors: true
  changed_when: false
  register: neovim_version_check

- name: Set is_neovim_present fact
  ansible.builtin.set_fact:
    is_neovim_present: '{{ not neovim_version_check.failed and neovim_version_check.stdout | regex_search(neovim_version | regex_escape()) }}'

- name: Download NeoVim Debian package
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.deb
    dest: /tmp/neovim.deb
  when: not is_neovim_present

- name: Install NeoVim Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/neovim.deb
  when: not is_neovim_present

- name: lazy.nvim repository is cloned
  ansible.builtin.git:
    repo: https://github.com/folke/lazy.nvim
    dest: ~/.local/share/nvim/lazy/lazy.nvim
    version: stable
    force: true

- name: NeoVim config directory is present
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: lazy.nvim lockfile is present
  ansible.builtin.copy:
    src: lazy-lock.json
    dest: ~/.config/nvim/lazy-lock.json
    mode: '0644'

- name: Vimscript config is absent
  ansible.builtin.file:
    path: ~/.config/nvim/init.vim
    state: absent

- name: NeoVim config is present
  ansible.builtin.copy:
    src: init.lua
    dest: ~/.config/nvim/init.lua
    mode: '0644'

- name: Lua folder is present
  ansible.builtin.file:
    path: ~/.config/nvim/lua
    state: directory
    mode: '1755'

- name: plugins.lua is present
  ansible.builtin.copy:
    src: plugins.lua
    dest: ~/.config/nvim/lua/plugins.lua
    mode: '0644'

- name: Node is present for installing language servers with npm
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: latest

  # TODO Add typescript compiler
- name: TypeScript language server is installed
  become: true
  community.general.npm:
    name: typescript-language-server
    global: true
    state: latest

- name: YAML language server is installed
  become: true
  community.general.npm:
    name: yaml-language-server
    global: true
    state: latest

- name: Dockerfile language server is installed
  become: true
  community.general.npm:
    name: dockerfile-language-server-nodejs
    global: true
    state: latest

- name: Emmet abbreviation language server is installed
  become: true
  community.general.npm:
    name: emmet-ls
    global: true
    state: latest

- name: Tailwind language server is installed
  become: true
  community.general.npm:
    name: '@tailwindcss/language-server'
    global: true
    state: latest

- name: Ansible language server is installed
  become: true
  community.general.npm:
    name: '@ansible/ansible-language-server'
    global: true
    state: latest

- name: Python development tools are present
  become: true
  ansible.builtin.pip:
    name:
      - pyright
      - mypy
      - pylint
      - black
    state: latest

- name: search tools are installed
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fd-find
    state: latest
