---
- name: Download Containerd Debian package
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_{{ containerd_version }}_amd64.deb
    dest: /tmp/containerd.deb

- name: Install Containerd Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/containerd.deb

- name: Download Docker CLI Debian package
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_{{ docker_version }}~3-0~ubuntu-jammy_amd64.deb
    dest: /tmp/docker-ce-cli.deb

- name: Install Docker CLI Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/docker-ce-cli.deb

- name: Download Docker Debian package
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_{{ docker_version }}~3-0~ubuntu-jammy_amd64.deb
    dest: /tmp/docker-ce.deb

- name: Install Docker Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/docker-ce.deb

- name: Download Docker Compose Debian package
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_{{ docker_compose_version }}~ubuntu-jammy_amd64.deb
    dest: /tmp/docker-compose.deb

- name: Install Docker Compose Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/docker-compose.deb
