---
- name: Debian backports repository is present
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-backports main
    state: present
  when: os_release == "debian-bullseye"

- name: Zsh and Git are installed
  become: true
  ansible.builtin.apt:
    name:
      - git
      - zsh
    default_release: "{{ ohmyzsh_git_apt_release }}"
    state: latest

- name: Oh My Zsh repository is cloned
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: Repository permissions are correct
  ansible.builtin.file:
    path: ~/.oh-my-zsh
    mode: go-w

- name: Zsh is the default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Node Version Manager is cloned
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm
    dest: ~/.nvm

- name: Fzf is installed for Zsh plugin
  become: true
  ansible.builtin.apt:
    name: fzf

- name: Pip is installed for Poetry download
  become: true
  ansible.builtin.apt:
    name: python3-pip

- name: Venv is installed for Pipx
  become: true
  ansible.builtin.apt:
    name: python3-venv

- name: Pipx is installed for Poetry download
  ansible.builtin.pip:
    name: pipx
    executable: /usr/bin/pip3
    extra_args: "{{ '--break-system-packages' if 'debian-bookworm' == os_release else '' }}"
    state: latest

- name: Poetry is installed for Zsh plugin
  community.general.pipx:
    name: poetry
    state: latest

- name: Node is present for installing Bitwarden CLI with npm
  become: true
  ansible.builtin.apt:
    name:
      - nodejs
      - npm
    state: latest

- name: Bitwarden CLI is installed for SSH key management
  become: true
  community.general.npm:
    name: "@bitwarden/cli"
    state: latest
    global: true

- name: Is_wsl fact is set
  ansible.builtin.set_fact:
    is_wsl: "{{ not not (ansible_kernel | regex_search('microsoft')) }}"

- name: .zshrc is present
  ansible.builtin.template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: u=rw,go=r

- name: Custom theme is present
  ansible.builtin.template:
    src: minima.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/minima.zsh-theme
    mode: u=rw,go=r

- name: Custom plugins are present
  ansible.builtin.copy:
    src: plugins
    dest: ~/.oh-my-zsh/custom
    mode: "1744"
