#!/bin/bash

if [ -z "$( ssh-add -L | grep "$(git config --global --get user.signingkey)" )" ];
then
	echo -e "\033[0;31mError:\033[0m Signing key not found in SSH agent."
	echo "Make sure your signing key is in SSH agent, and/or SSH agent forwarding is working."
	exit -1
fi
