---
- name: NeoVim Ubuntu PPA is present
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Latest NeoVim is installed
  become: true
  ansible.builtin.apt:
    name: neovim
    state: latest
    update_cache: yes

- name: NeoVim config is present
  ansible.builtin.template:
    src: init.vim
    dest: ~/.config/nvim/init.vim
    backup: yes
    mode: u=rw,go=r
