---
- name: Get NeoVim version
  ansible.builtin.command: nvim --version
  ignore_errors: true
  changed_when: false
  register: neovim_version_check

- name: Set is_neovim_present fact
  ansible.builtin.set_fact:
    is_neovim_present: '{{ not neovim_version_check.failed and neovim_version_check.stdout | regex_search(neovim_version | regex_escape()) }}'

- name: Download NeoVim Debian package
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux64.deb
    dest: /tmp/neovim.deb
  when: not is_neovim_present

- name: Install NeoVim Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/neovim.deb
  when: not is_neovim_present

- name: packer.nvim repository is cloned
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim.git
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim

- name: NeoVim config is present
  ansible.builtin.template:
    src: init.vim
    dest: ~/.config/nvim/init.vim
    backup: yes
    mode: u=rw,go=r

- name: Lua folder is present
  ansible.builtin.file:
    path: ~/.config/nvim/lua
    state: directory

- name: plugins.lua is present
  ansible.builtin.template:
    src: plugins.lua
    dest: ~/.config/nvim/lua/plugins.lua
    backup: yes
    mode: u=rw,go=r

  # TODO Add typescript compiler
- name: TypeScript language server is installed
  community.general.npm:
    name: typescript-language-server
    global: true
    state: latest

- name: YAML language server is installed
  community.general.npm:
    name: yaml-language-server
    global: true
    state: latest

- name: Dockerfile language server is installed
  community.general.npm:
    name: dockerfile-language-server-nodejs
    global: true
    state: latest

# Uncomment once this merges:
# https://github.com/aca/emmet-ls/pull/39
# - name: Emmet abbreviation language server is installed
#   community.general.npm:
#     name: emmet-ls
#     global: true
#     state: latest

- name: Python language server is installed
  ansible.builtin.pip:
    name: pyright
    state: latest

- name: search tools are installed
  become: true
  ansible.builtin.apt:
    name:
      - ripgrep
      - fd-find
    state: latest

- name: Sync Packer dependencies
  ansible.builtin.command: nvim --headless +PackerSync +q

